/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import BGBG from "./BGBG";
import ElementsLineGorizontal from "./ElementsLineGorizontal";
import ElementsLineVertical from "./ElementsLineVertical";
import { Text, View } from "@aws-amplify/ui-react";
export default function BGGrids2(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="1424px"
      height="790px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "BGGrids2")}
      {...rest}
    >
      <BGBG
        width="1424px"
        height="790px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="0%"
        left="0%"
        right="0%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Elements / BG")}
      ></BGBG>
      <View
        padding="0px 0px 0px 0px"
        width="1294px"
        height="589px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="100px"
        left="90px"
        {...getOverrideProps(overrides, "Lines")}
      >
        <ElementsLineGorizontal
          width="1294px"
          height="1px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="99.83%"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Gorizontal0296")}
        ></ElementsLineGorizontal>
        <ElementsLineGorizontal
          width="1294px"
          height="1px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="16.64%"
          bottom="83.19%"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Gorizontal0297")}
        ></ElementsLineGorizontal>
        <ElementsLineGorizontal
          width="1294px"
          height="1px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="33.28%"
          bottom="66.55%"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Gorizontal0298")}
        ></ElementsLineGorizontal>
        <ElementsLineGorizontal
          width="1294px"
          height="1px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="49.92%"
          bottom="49.92%"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Gorizontal0299")}
        ></ElementsLineGorizontal>
        <ElementsLineGorizontal
          width="1294px"
          height="1px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="66.55%"
          bottom="33.28%"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Gorizontal0300")}
        ></ElementsLineGorizontal>
        <ElementsLineGorizontal
          width="1294px"
          height="1px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="83.19%"
          bottom="16.64%"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Gorizontal0301")}
        ></ElementsLineGorizontal>
        <ElementsLineGorizontal
          width="1294px"
          height="1px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="99.83%"
          bottom="0%"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Gorizontal0302")}
        ></ElementsLineGorizontal>
        <ElementsLineVertical
          width="1px"
          height="589px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="0%"
          right="99.92%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Vertical0303")}
        ></ElementsLineVertical>
        <ElementsLineVertical
          width="1px"
          height="589px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="8.35%"
          right="91.58%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Vertical0304")}
        ></ElementsLineVertical>
        <ElementsLineVertical
          width="1px"
          height="589px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="16.69%"
          right="83.23%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Vertical0305")}
        ></ElementsLineVertical>
        <ElementsLineVertical
          width="1px"
          height="589px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="24.96%"
          right="74.96%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Vertical0306")}
        ></ElementsLineVertical>
        <ElementsLineVertical
          width="1px"
          height="589px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="33.31%"
          right="66.62%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Vertical0307")}
        ></ElementsLineVertical>
        <ElementsLineVertical
          width="1px"
          height="589px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="41.65%"
          right="58.27%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Vertical0308")}
        ></ElementsLineVertical>
        <ElementsLineVertical
          width="1px"
          height="589px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="50%"
          right="49.92%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Vertical0309")}
        ></ElementsLineVertical>
        <ElementsLineVertical
          width="1px"
          height="589px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="58.27%"
          right="41.65%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Vertical0310")}
        ></ElementsLineVertical>
        <ElementsLineVertical
          width="1px"
          height="589px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="66.62%"
          right="33.31%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Vertical0311")}
        ></ElementsLineVertical>
        <ElementsLineVertical
          width="1px"
          height="589px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="74.96%"
          right="24.96%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Vertical0312")}
        ></ElementsLineVertical>
        <ElementsLineVertical
          width="1px"
          height="589px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="83.31%"
          right="16.62%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Vertical0313")}
        ></ElementsLineVertical>
        <ElementsLineVertical
          width="1px"
          height="589px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="91.58%"
          right="8.35%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Vertical0314")}
        ></ElementsLineVertical>
        <ElementsLineVertical
          width="1px"
          height="589px"
          display="block"
          gap="unset"
          alignItems="unset"
          justifyContent="unset"
          position="absolute"
          top="0%"
          bottom="0%"
          left="99.92%"
          right="0%"
          padding="0px 0px 0px 0px"
          {...getOverrideProps(overrides, "Elements / Line / Vertical0315")}
        ></ElementsLineVertical>
      </View>
      <View
        width="1236px"
        height="20px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        overflow="hidden"
        position="absolute"
        top="91.01%"
        bottom="6.46%"
        left="6.32%"
        right="6.88%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Horizontal")}
      >
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="0%"
          right="97.57%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="1 / 12"
          {...getOverrideProps(overrides, "1 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="8.74%"
          right="88.51%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="2 / 12"
          {...getOverrideProps(overrides, "2 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="17.56%"
          right="79.69%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="3 / 12"
          {...getOverrideProps(overrides, "3 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="26.38%"
          right="70.87%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="4 / 12"
          {...getOverrideProps(overrides, "4 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="35.19%"
          right="62.06%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="5 / 12"
          {...getOverrideProps(overrides, "5 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="44.01%"
          right="53.24%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="6 / 12"
          {...getOverrideProps(overrides, "6 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="52.83%"
          right="44.5%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="7 / 12"
          {...getOverrideProps(overrides, "7 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="61.65%"
          right="35.6%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="8 / 12"
          {...getOverrideProps(overrides, "8 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="70.47%"
          right="26.78%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="9 / 12"
          {...getOverrideProps(overrides, "9 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="79.29%"
          right="17.48%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="10 / 12"
          {...getOverrideProps(overrides, "10 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="88.11%"
          right="9.14%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="11 / 12"
          {...getOverrideProps(overrides, "11 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="96.93%"
          right="0%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="12 / 12"
          {...getOverrideProps(overrides, "12 / 12")}
        ></Text>
      </View>
      <View
        width="29px"
        height="608px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        overflow="hidden"
        position="absolute"
        top="11.39%"
        bottom="11.65%"
        left="2.11%"
        right="95.86%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Vertical")}
      >
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 294px)"
          left="0%"
          right="6.9%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="700"
          {...getOverrideProps(overrides, "700")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 196px)"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="600"
          {...getOverrideProps(overrides, "600")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 98px)"
          left="0%"
          right="3.45%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="500"
          {...getOverrideProps(overrides, "500")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="0%"
          right="3.45%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="400"
          {...getOverrideProps(overrides, "400")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - -98px)"
          left="0%"
          right="3.45%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="300"
          {...getOverrideProps(overrides, "300")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - -196px)"
          left="0%"
          right="3.45%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="200"
          {...getOverrideProps(overrides, "200")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - -294px)"
          left="0%"
          right="17.24%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="100"
          {...getOverrideProps(overrides, "100")}
        ></Text>
      </View>
    </View>
  );
}
