/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import BGBG from "./BGBG";
import { Text, View } from "@aws-amplify/ui-react";
import ElementsLineGorizontal from "./ElementsLineGorizontal";
export default function BGGrids1(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="1424px"
      height="790px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "BGGrids1")}
      {...rest}
    >
      <BGBG
        width="1424px"
        height="790px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="0%"
        left="0%"
        right="0%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Elements / BG")}
      ></BGBG>
      <View
        width="1236px"
        height="20px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        overflow="hidden"
        position="absolute"
        top="91.01%"
        bottom="6.46%"
        left="8.36%"
        right="4.85%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Horizontal")}
      >
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="0%"
          right="97.57%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="1 / 12"
          {...getOverrideProps(overrides, "1 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="8.74%"
          right="88.51%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="2 / 12"
          {...getOverrideProps(overrides, "2 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="17.56%"
          right="79.69%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="3 / 12"
          {...getOverrideProps(overrides, "3 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="26.38%"
          right="70.87%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="4 / 12"
          {...getOverrideProps(overrides, "4 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="35.19%"
          right="62.06%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="5 / 12"
          {...getOverrideProps(overrides, "5 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="44.01%"
          right="53.24%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="6 / 12"
          {...getOverrideProps(overrides, "6 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="52.83%"
          right="44.5%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="7 / 12"
          {...getOverrideProps(overrides, "7 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="61.65%"
          right="35.6%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="8 / 12"
          {...getOverrideProps(overrides, "8 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="70.47%"
          right="26.78%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="9 / 12"
          {...getOverrideProps(overrides, "9 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="79.29%"
          right="17.48%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="10 / 12"
          {...getOverrideProps(overrides, "10 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="88.11%"
          right="9.14%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="11 / 12"
          {...getOverrideProps(overrides, "11 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="96.93%"
          right="0%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="12 / 12"
          {...getOverrideProps(overrides, "12 / 12")}
        ></Text>
      </View>
      <View
        width="29px"
        height="608px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        overflow="hidden"
        position="absolute"
        top="11.39%"
        bottom="11.65%"
        left="2.11%"
        right="95.86%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Vertical")}
      >
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 294px)"
          left="0%"
          right="6.9%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="700"
          {...getOverrideProps(overrides, "700")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 196px)"
          left="0%"
          right="0%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="600"
          {...getOverrideProps(overrides, "600")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 98px)"
          left="0%"
          right="3.45%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="500"
          {...getOverrideProps(overrides, "500")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="0%"
          right="3.45%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="400"
          {...getOverrideProps(overrides, "400")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - -98px)"
          left="0%"
          right="3.45%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="300"
          {...getOverrideProps(overrides, "300")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - -196px)"
          left="0%"
          right="3.45%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="200"
          {...getOverrideProps(overrides, "200")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - -294px)"
          left="0%"
          right="17.24%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="100"
          {...getOverrideProps(overrides, "100")}
        ></Text>
      </View>
      <ElementsLineGorizontal
        width="1294px"
        height="1px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.66%"
        bottom="87.22%"
        left="6.32%"
        right="2.81%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(0,0,0,1)"
        opacity="0.10000000149011612"
        {...getOverrideProps(overrides, "Elements / Line / Gorizontal0441")}
      ></ElementsLineGorizontal>
      <ElementsLineGorizontal
        width="1294px"
        height="1px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="25.06%"
        bottom="74.81%"
        left="6.32%"
        right="2.81%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(0,0,0,1)"
        opacity="0.10000000149011612"
        {...getOverrideProps(overrides, "Elements / Line / Gorizontal0442")}
      ></ElementsLineGorizontal>
      <ElementsLineGorizontal
        width="1294px"
        height="1px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="37.47%"
        bottom="62.41%"
        left="6.32%"
        right="2.81%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(0,0,0,1)"
        opacity="0.10000000149011612"
        {...getOverrideProps(overrides, "Elements / Line / Gorizontal0443")}
      ></ElementsLineGorizontal>
      <ElementsLineGorizontal
        width="1294px"
        height="1px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="49.87%"
        bottom="50%"
        left="6.32%"
        right="2.81%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(0,0,0,1)"
        opacity="0.10000000149011612"
        {...getOverrideProps(overrides, "Elements / Line / Gorizontal0444")}
      ></ElementsLineGorizontal>
      <ElementsLineGorizontal
        width="1294px"
        height="1px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="62.28%"
        bottom="37.59%"
        left="6.32%"
        right="2.81%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(0,0,0,1)"
        opacity="0.10000000149011612"
        {...getOverrideProps(overrides, "Elements / Line / Gorizontal0445")}
      ></ElementsLineGorizontal>
      <ElementsLineGorizontal
        width="1294px"
        height="1px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="74.68%"
        bottom="25.19%"
        left="6.32%"
        right="2.81%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(0,0,0,1)"
        opacity="0.10000000149011612"
        {...getOverrideProps(overrides, "Elements / Line / Gorizontal0446")}
      ></ElementsLineGorizontal>
      <ElementsLineGorizontal
        width="1294px"
        height="1px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="87.09%"
        bottom="12.78%"
        left="6.32%"
        right="2.81%"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(0,0,0,1)"
        opacity="0.10000000149011612"
        {...getOverrideProps(overrides, "Elements / Line / Gorizontal0447")}
      ></ElementsLineGorizontal>
    </View>
  );
}
