/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import BGBG from "./BGBG";
import ElementsLineVertical from "./ElementsLineVertical";
import { Text, View } from "@aws-amplify/ui-react";
export default function BGGrids3(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="1424px"
      height="790px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "BGGrids3")}
      {...rest}
    >
      <BGBG
        width="1424px"
        height="790px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="0%"
        left="0%"
        right="0%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Elements / BG")}
      ></BGBG>
      <ElementsLineVertical
        width="1px"
        height="589px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.66%"
        bottom="12.78%"
        left="11.1%"
        right="88.83%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Elements / Line / Vertical0100")}
      ></ElementsLineVertical>
      <ElementsLineVertical
        width="1px"
        height="589px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.66%"
        bottom="12.78%"
        left="18.89%"
        right="81.04%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Elements / Line / Vertical0102")}
      ></ElementsLineVertical>
      <ElementsLineVertical
        width="1px"
        height="589px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.66%"
        bottom="12.78%"
        left="26.76%"
        right="73.17%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Elements / Line / Vertical0103")}
      ></ElementsLineVertical>
      <ElementsLineVertical
        width="1px"
        height="589px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.66%"
        bottom="12.78%"
        left="34.55%"
        right="65.38%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Elements / Line / Vertical0104")}
      ></ElementsLineVertical>
      <ElementsLineVertical
        width="1px"
        height="589px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.66%"
        bottom="12.78%"
        left="42.35%"
        right="57.58%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Elements / Line / Vertical0105")}
      ></ElementsLineVertical>
      <ElementsLineVertical
        width="1px"
        height="589px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.66%"
        bottom="12.78%"
        left="50.21%"
        right="49.72%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Elements / Line / Vertical0106")}
      ></ElementsLineVertical>
      <ElementsLineVertical
        width="1px"
        height="589px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.66%"
        bottom="12.78%"
        left="58.01%"
        right="41.92%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Elements / Line / Vertical0107")}
      ></ElementsLineVertical>
      <ElementsLineVertical
        width="1px"
        height="589px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.66%"
        bottom="12.78%"
        left="65.87%"
        right="34.06%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Elements / Line / Vertical0108")}
      ></ElementsLineVertical>
      <ElementsLineVertical
        width="1px"
        height="589px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.66%"
        bottom="12.78%"
        left="73.67%"
        right="26.26%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Elements / Line / Vertical0109")}
      ></ElementsLineVertical>
      <ElementsLineVertical
        width="1px"
        height="589px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.66%"
        bottom="12.78%"
        left="81.46%"
        right="18.47%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Elements / Line / Vertical0110")}
      ></ElementsLineVertical>
      <ElementsLineVertical
        width="1px"
        height="589px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.66%"
        bottom="12.78%"
        left="89.33%"
        right="10.6%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Elements / Line / Vertical0111")}
      ></ElementsLineVertical>
      <ElementsLineVertical
        width="1px"
        height="589px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="12.66%"
        bottom="12.78%"
        left="97.12%"
        right="2.81%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Elements / Line / Vertical0112")}
      ></ElementsLineVertical>
      <View
        width="1194px"
        height="20px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        overflow="hidden"
        position="absolute"
        top="91.01%"
        bottom="6.46%"
        left="11.1%"
        right="5.06%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Horizontal")}
      >
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="0%"
          right="97.99%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="100"
          {...getOverrideProps(overrides, "1 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="9.3%"
          right="88.36%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="200"
          {...getOverrideProps(overrides, "2 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="18.68%"
          right="78.98%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="300"
          {...getOverrideProps(overrides, "3 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="27.97%"
          right="69.68%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="400"
          {...getOverrideProps(overrides, "4 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="37.27%"
          right="60.39%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="500"
          {...getOverrideProps(overrides, "5 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="46.65%"
          right="50.92%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="600"
          {...getOverrideProps(overrides, "6 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="55.95%"
          right="41.79%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="700"
          {...getOverrideProps(overrides, "7 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="65.33%"
          right="32.33%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="800"
          {...getOverrideProps(overrides, "8 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="83.92%"
          right="13.23%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="1000"
          {...getOverrideProps(overrides, "10 / 12")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="93.3%"
          right="4.36%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="1100"
          {...getOverrideProps(overrides, "11 / 12")}
        ></Text>
      </View>
      <Text
        fontFamily="DM Sans"
        fontSize="14px"
        fontWeight="400"
        color="rgba(0,0,0,1)"
        lineHeight="20px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="unset"
        height="unset"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="91.01%"
        bottom="6.46%"
        left="73.67%"
        right="24.3%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="900"
        {...getOverrideProps(overrides, "9 / 12")}
      ></Text>
      <View
        width="83px"
        height="572px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        overflow="hidden"
        position="absolute"
        top="13.67%"
        bottom="13.92%"
        left="2.11%"
        right="92.06%"
        padding="0px 0px 0px 0px"
        {...getOverrideProps(overrides, "Vertical")}
      >
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 276px)"
          left="0%"
          right="2.41%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="02 Nov 2019"
          {...getOverrideProps(overrides, "02 Nov 2019")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 184px)"
          left="0%"
          right="14.46%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="11 Mar 2019"
          {...getOverrideProps(overrides, "11 Mar 2019")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 92px)"
          left="0%"
          right="1.2%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="29 May 2019"
          {...getOverrideProps(overrides, "29 May 2019")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - 0px)"
          left="0%"
          right="3.61%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="06 Jan 2019"
          {...getOverrideProps(overrides, "06 Jan 2019")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - -92px)"
          left="0%"
          right="10.84%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="14 Jan 2019"
          {...getOverrideProps(overrides, "14 Jan 2019")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - -184px)"
          left="0%"
          right="8.43%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="13 Nov 2019"
          {...getOverrideProps(overrides, "13 Nov 2019")}
        ></Text>
        <Text
          fontFamily="DM Sans"
          fontSize="14px"
          fontWeight="400"
          color="rgba(0,0,0,1)"
          lineHeight="20px"
          textAlign="left"
          display="block"
          direction="column"
          justifyContent="unset"
          width="unset"
          height="unset"
          gap="unset"
          alignItems="unset"
          position="absolute"
          top="calc(50% - 10px - -276px)"
          left="0%"
          right="2.41%"
          padding="0px 0px 0px 0px"
          whiteSpace="pre-wrap"
          children="03 Mar 2019"
          {...getOverrideProps(overrides, "03 Mar 2019")}
        ></Text>
      </View>
    </View>
  );
}
